### ISSUE TITLE
Never get DRDY

### ISSUE THREAD

**Issue by philgrim2** [Protocentral/ADS1292rShield_Breakout#4]
Using the breakout board with an Uno R3.
Put in some Serial.println settings to try to discover why I don't get results.
DRDY never goes low.
I have two boards, same results with both.

**Comment by VenkateshBhat** [comment]
Could you please attach the connection setup?

**Comment by gcmike** [comment]
Same issue here. Any updates?

**Comment by VenkateshBhat** [comment]
@gcmike 
Sorry for the inconvenience caused,
Please provide us the additional details/share the screenshots.

**Comment by gcmike** [comment]
Currently we are using MSP430F5510 to communicate with this. The spi setting seems to be working, but the DRDY pin is kept high. The GPIO pins seems not specifically setup inside the program, and the default would be input? Should they be pulled low with resistors?
Another question, is the higher grade capacitors needed?

**Comment by VenkateshBhat** [comment]
@gcmike thanks for sharing,
Couple of things:
- If your msp430xxx is 3.3V tolerable change the jumper setting on the breakout to 3.3V. By default it will be 5V.
- No additional pulldown is required since there is a on board level converter.
Ensure START and PWDN/RESET are pulled high.
![ads1292r-ecgrespiration-breakout-board](https://user-images.githubusercontent.com/6176131/31043817-3ba15cfc-a5e0-11e7-84da-bfbaab0344be.jpg)
